@startuml


actor       Student      as student


boundary "Area of registration" as register
boundary "Area de escolha dos livros" as dashboard

boundary "book page" as book
boundary "Area do usuario" as dash

control "back-end controller" as controller

database    database    as database

group Login or registration

student -> register
register -> database
database -> dashboard

end


group Reserva de titulo 
dashboard -> book : Selecionar o livro de interesse
book -> controller : Confiar selecao do livro

controller -> database : Reservar titulo
database -> dashboard : Atualizar a pagina
end

group Apagar um titulo
controller -> dash : Buscar todos os titulos do usuario
dash -> controller : apagar os títulos
end

group Adicionar um titulo
controller -> dash : Buscar todos os titulos
dash -> controller : Aplicar as alterações desejadas
end












@enduml
alt successful case

    Bob -> Alice: Authentication Accepted
    Ccoo -> Bob : auth\

else some kind of failure

    Bob -> Alice: Authentication Failure
    group My own label
    Alice -> Log : Log attack start
        loop 1000 times
            Alice -> Bob: DNS Attack
        end
    Alice -> Log : Log attack end
    end

else Another type of failure

   Bob -> Alice: Please repeat

end